@port = 3000

# =================================================================================================
#  GENERAL SERVER API                                                                                          
# =================================================================================================

###

GET http://localhost:{{port}}/

###

GET http://localhost:{{port}}/server-runtime


# =================================================================================================
#  GET RUN BY ID                                                                                        
# =================================================================================================

### correct ID #1

GET http://localhost:{{port}}/run/69625f10c3dfc91345faf311

### correct ID #2

GET http://localhost:{{port}}/run/69625fd283de3e628cbb0b0b

### incorrect ID #1

GET http://localhost:{{port}}/run/69625f10c4afc91345faf311

### incorrect ID #2 (wrong format)

GET http://localhost:{{port}}/run/000000zdg000000000000000000